config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, :snippets, :attempts

  namespace :api do
    resources :users, :snippets, :attempts
  end

  get '/session/new', to: 'session#new'
  post '/session', to: 'session#create'
  delete '/session', to: 'session#destroy'

  get '/', to: 'users#home'
  # get '/snippet/index', to: 'snippets#index'
  get '/languages', to: 'snippets#languages'
  get '/languages/javascript', to: 'snippets#javascript'
  get '/languages/ruby', to: 'snippets#ruby'
  get '/languages/other', to: 'snippets#others'
end

app/models/snippet.rb
class Snippet < ApplicationRecord
  belongs_to :user
  has_many :attempts, dependent: :destroy
  validates :name , :description , :language , :body , :word_count , presence: true
  validates :name , uniqueness: true

  def users_played
    @myId = self.id
    @attempts = Attempt.where('snippet_id' => @myId).order('score DESC').to_a.uniq {|attempt| attempt[:user_id] }.length
  end
end

app/controllers/snippet_controller.rb
class SnippetController < ApplicationController
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def show
    @snippet = Snippet.find(params[:id])
    body = @snippet.body.delete("\r")
    @array = body.split("").push(" ")

    if @snippet.language == 'javascript'
      @header_snippet_name = @snippet.name.gsub(/\s/, '_') + '.js'
    elsif @snippet.language == 'ruby'
      @header_snippet_name = @snippet.name.gsub(/\s/, '_') + '.rb'
    else
      @header_snippet_name = @snippet.name
    end

    if !!session[:user_id]
      @history = Attempt.where('user_id' => User.find(session[:user_id]).id, 'snippet_id' => @snippet.id).order('id DESC').limit(3)

      @time_played = []
      @history.each do |attempt|

        sec_diff = (Time.zone.now - attempt.updated_at).floor
        minute_diff = (sec_diff / 60).floor
        hour_diff = (minute_diff / 60).floor
        day_diff = (hour_diff / 24).floor
        year_diff = (day_diff / 365).floor

        if sec_diff < 2
          time_string = "#{sec_diff} second ago"
        elsif sec_diff < 60
          time_string = "#{sec_diff} seconds ago"
        elsif minute_diff < 2
          time_string = "#{minute_diff} minute ago"
        elsif minute_diff < 60
          time_string = "#{minute_diff} minutes ago"
        elsif hour_diff < 2
          time_string = "#{hour_diff} hour ago"
        elsif hour_diff < 24
          time_string = "#{hour_diff} hours ago"
        elsif day_diff < 2
          time_string = "#{day_diff} day ago"
        elsif day_diff < 365
          time_string = "#{day_diff} days ago"
        elsif year_diff < 2
          time_string = "#{year_diff} year ago"
        else
          time_string = "#{year_diff} years ago"
        end

        @time_played.push(time_string)
      end
    end

    @leaderboard = Attempt.where('snippet_id' => @snippet.id).order('score DESC').to_a.uniq {|attempt| attempt[:user_id] }[0,10]

  end

  def new
    @errors = {}
    @snippet = Snippet.new
  end

  def create
    @snippet = Snippet.new
    @snippet.description = params[:description]
    @snippet.name = params[:name]
    @snippet.user_id = session[:user_id]
    @snippet.body = params[:body].split("\n").map{|line|line.rstrip}.join("\n").strip
    @snippet.language = params[:language]
    @snippet.word_count = @snippet.body.scan(/[[:alpha:]]+/).count

    @errors = {}
    if @snippet.save
      flash[:success] = "Snippet added successfully"
      redirect_to "/snippets/#{@snippet.id}"
    else
      @snippet.errors.messages.each do |key, value|
        if value.any?
          @errors[key] = '*' + value.join(', ')
        end
      end
      flash[:danger] = "Something went wrong. Try again."
      render :new
    end
  end

  def edit
    @errors = {}
    @snippet = Snippet.find(params[:id])

    if session[:user_id] != @snippet.user_id && User.find(session[:user_id]).username != "kings"
      redirect_to '/'
    end

  end

  def update
    @snippet = Snippet.find(params[:id])

    if session[:user_id] != @snippet.user_id && User.find(session[:user_id]).username != "kings"
      redirect_to '/'
    end

    @snippet.description = params[:description]
    @snippet.name = params[:name]
    @snippet.user_id = session[:user_id]
    @snippet.body = params[:body].split("\n").map{|line|line.rstrip}.join("\n").strip
    @snippet.language = params[:language]
    @snippet.word_count = @snippet.body.scan(/[[:alpha:]]+/).count

    @errors = {}
    if @snippet.save
      flash[:success] = "Snippet updated successfully"
      redirect_to "/snippets/#{@snippet.id}"
    else
      @snippet.errors.messages.each do |key, value|
        if value.any?
          @errors[key] = '*' + value.join(', ')
        end
      end
      flash[:danger] = "Something went wrong. Try again."
      render :edit
    end
  end

  def destroy
    snippet = Snippet.find(params[:id])
    if session[:user_id] != snippet.user_id
      redirect_to '/'
    end
    snippet.destroy
    flash[:success] = "Snippet removed successfully"
    redirect_to "/users/#{session[:user_id]}"
  end

  def languages
    @snippets = Snippet.all
    @attempts = Attempt.order(score: :desc).to_a.uniq {|attempt|  [attempt[:user_id],attempt[:snippet_id]]  }[0,10]
  end

  def javascript
    @snippets = Snippet.where(language: 'javascript')
    @snippets_pop = Snippet.joins(:attempts).where(language: 'javascript').group(:id).order("count(*) desc")
    @attempts = Attempt.joins(:snippet).where(snippets: {language: :javascript }).order(score: :desc).to_a.uniq {|attempt|  [attempt[:user_id],attempt[:snippet_id]]  }[0,10]
  end

  def ruby
    @snippets = Snippet.where(language: 'ruby')
    @snippets_pop = Snippet.joins(:attempts).where(language: 'ruby').group(:id).order("count(*) desc")
    @attempts = Attempt.joins(:snippet).where(snippets: {language: :ruby }).order(score: :desc).to_a.uniq {|attempt|  [attempt[:user_id],attempt[:snippet_id]]  }[0,10]
  end

  def others
    @snippets = Snippet.where(language: 'other')
    @snippets_pop = Snippet.joins(:attempts).where(language: 'other').group(:id).order("count(*) desc")
    @attempts = Attempt.joins(:snippet).where(snippets: {language: :other }).order(score: :desc).to_a.uniq {|attempt|  [attempt[:user_id],attempt[:snippet_id]]  }[0,10]
  end
end

app/helpers/snippet_helper.rb
module SnippetHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/edit.html.erb
<div class="snippet-new-wrapper">
  <div class="back-btn">
    <a href="/users/<%= current_user.id %>"><button class="btn-back">Back To Your Profile</button></a>
  </div>

  <div class="snippet-new-form">
    <%= form_tag snippet_path , method: 'patch' do %>

      <div class="snippet-name form-group">
        <input id="name" class="" name="name" type="text" value="<%= @snippet.name %>" placeholder="Snippet Name" >
        <p class="danger"><%= @errors[:name] %></p>
      </div>

      <div class="snippet-description form-group">
        <textarea id="description" class="" type="text" name="description" placeholder="Description" rows="1" cols="60"><%= @snippet.description %></textarea>
        <p class="danger"><%= @errors[:description] %></p>
      </div>

      <div class="snippet-language">
        <span class="fancyArrow"></span>
        <select id="language" class="" name="language" value="<%= @snippet.language %>">
          <option value="javascript">JavaScript</option>
          <option value="ruby">Ruby</option>
          <option value="other">Other</option>
        </select>
        <p class="danger"><%= @errors[:language] %></p>
      </div>

      <div class="snippet-body form-group">
        <textarea id="snippet-body" class="" type="text" name="body" rows="8" cols="60" placeholder="Snippet Code"><%= @snippet.body %></textarea>
        <p class="danger"><%= @errors[:body] %></p>
      </div>

      <div class="btns">
        <div class="snippet-btn">
          <button class="btn-snippet">Update</button>
        </div>

    <% end %>

      <div class="snippet-delete-btn">
        <%= form_tag snippet_path , method: 'delete' do %>

          <button class="btn-snippet">Delete</button>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/snippets/index.html.erb
<!-- link_to "edit snippet 1" , "/snippets/#{@snippet.id}/edit" , id:'1'
-->


<!-- _________________________ Ruby ________________________ -->
<h2><a href="/javascript">JavaScript</a></h2>
<h2><a href="/ruby">Ruby</a></h2>
<h2><a href="/other">Others</a></h2>



<style>
  .section-js {
    display: block;
    width: 100%;
    background-color: #3e9a82;
  }

  .section-ruby {
    display: block;
    width: 100%;
    height: 300px;
    background-color: #f0c79c;
  }

  .list {
    width: 25%;
    text-align: center;
    vertical-align: top;
    display: inline-block;
  }

  .list h3{
    margin-bottom: 10px;
    font-weight: bold;
  }

  .score-board {
    display: inline-block;
    width: 25%;
    text-align: center;
  }

  .score-board h3{
    margin-bottom: 10px;
    font-weight: bold;
  }
</style>

app/views/snippets/javascript.html.erb
<div class="language-container">
  <div class="back-btn">
    <a href="/languages"><button class="btn-back">Back To Languages</button></a>
  </div>
  <div class="left-side">
    <h3>JavaScript Snippets</h3>

    <div class="div-snippets-list">
      <table class="table table-striped">
        <tr>
          <th  class="column-title">Name</th>
          <th class="column-title">Description</th>
          <th class="column-title">Word Count</th>
          <th class="column-title"># Players played</th>
          <th></th>
        </tr>
        <% @snippets_pop.each do |snippet| %>
          <tr class='clickable-row' data-href='/snippets/<%= snippet.id %>'>
            <td><%= link_to( snippet.name, snippet_path(snippet)) %></td>
            <td><%= truncate(snippet.description, length: 100) %></td>
            <td><%= snippet.word_count %></td>
            <td><%= snippet.users_played %></td>
            <td><button class="btn btn-default">Play</button></td>
          </tr>
        <% end %>
        <% @snippets.each do |snippet| %>
          <% if !@snippets_pop.include? snippet%>
            <tr class='clickable-row' data-href='/snippets/<%= snippet.id %>'>
              <td><%= link_to( snippet.name, snippet_path(snippet)) %></td>
              <td><%= truncate(snippet.description, length: 100) %></td>
              <td><%= snippet.word_count %></td>
              <td><%= snippet.users_played %></td>
              <td><button class="btn btn-default">Play</button></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>

  <div class="right-side">
    <div class="div-language-score-board">
      <h3>Score Board</h3>
      <table class="table table-striped">
        <tr>
          <th>#</th>
          <th> Username </th>
          <th> Snippet </th>
          <th> Score </th>
        </tr>
        <% if @attempts.empty? %>
        <tr>
          <td> --- </td>
          <td> --- </td>
          <td> No entries </td>
          <td> --------- </td>
        </tr>
        <% else %>
          <% @attempts.each_with_index do |attempt, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><a href="/users/<%= attempt.user.id %>"><%= attempt.user.username %></a></td>
            <td><%= link_to( attempt.snippet.name, snippet_path(attempt.snippet)) %></td>
            <td><%= attempt.score %></td>
          </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/snippets/languages.html.erb
<div class="snippets-language-wrapper">

  <div class="languages-wrapper">
    <h2>Select a Language to Start Typing</h2>

    <a href="/languages/javascript">
      <div class="language-card">
        <h2>JavaScript</h2>
        <img src="https://www.voice-group.co.uk/wp-content/uploads/voice_group_web-languages-logos-javascript.png" alt="">
      </div>
    </a>

    <a href="/languages/ruby">
      <div class="language-card">
        <h2>Ruby</h2>
        <img src="http://js.judykat.com/ken-judy/wp-content/uploads/2014/09/ruby.png?b5a88a" alt="">
      </div>
    </a>

    <a href="/languages/other">
      <div class="language-card">
        <h2>Others</h2>
        <img src="http://4vector.com/i/free-vector-book_102706_Book.png" alt="">
      </div>
    </a>
  </div>

  <div class="language-leaderboard">
    <h2>SpeedCoder Leader Board</h3>

    <div class="language-score-board">
      <table class="table table-striped">
        <tr>
          <th>#</th>
          <th>Snippet Name</th>
          <th>Username</th>
          <th>Score</th>
        </tr>
        <% if @attempts.empty? %>
          <tr>
            <td> --- </td>
            <td> No entries </td>
            <td> --------- </td>
          </tr>
        <% else %>
          <% @position = 1 %>
          <% @attempts.each do |attempt| %>
            <tr>
              <td><%= @position %></td>
              <td><%= link_to(attempt.snippet.name, snippet_path(attempt.snippet)) %></td>
              <td><%= link_to(attempt.user.username, user_path(attempt.user)) %></td>
              <td><%= attempt.score %></td>
            </tr>
            <% @position = @position + 1 %>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>

</div>

app/views/snippets/new.html.erb
<div class="snippet-new-wrapper">
  <div class="back-btn">
    <a href="/users/<%= current_user.id %>"><button class="btn-back">Back To Your Profile</button></a>
  </div>

  <div class="snippet-new-form">
    <%= form_tag '/snippets' , method: 'post' do %>

      <div class="snippet-name form-group">
        <input id="name" class="" name="name" type="text" placeholder="Snippet Name" value="<%= @snippet.name %>" >
        <p class="danger"><%= @errors[:name] %></p>
      </div>

      <div class="snippet-description form-group">
        <textarea id="description" class="" type="text" name="description" placeholder="Description" rows="1" cols="60"><%= @snippet.description %></textarea>
        <p class="danger"><%= @errors[:description] %></p>
      </div>

      <div class="snippet-language">
        <span class="fancyArrow"></span>
        <select id="language-new" class="" name="language"  >
          <option value="javascript" <% if @snippet.language == 'javascript' %> selected <% end %> >JavaScript</option>
          <option value="ruby" <% if @snippet.language == 'ruby' %> selected <% end %>>Ruby</option>
          <option value="other" <% if @snippet.language == 'other' %> selected <% end %>>Other</option>
        </select>
        <p class="danger"><%= @errors[:language] %></p>
      </div>

      <div class="snippet-body form-group">
        <textarea id="snippet-body" type="text" name="body" rows="8" cols="60" placeholder="Snippet Code"> <%= @snippet.body %></textarea>
        <p class="danger"><%= @errors[:body] %></p>
      </div>

      <div class="snippet-btn">
        <button class="btn-snippet">Submit</button>
      </div>
    <% end %>
  </div>
</div>

app/views/snippets/others.html.erb
<div class="back-btn">
  <a href="/languages"><button class="btn-back">Back To Languages</button></a>
</div>
  <div class="left-side">
    <h3>Other Snippets</h3>
    <div class="div-snippets-list">
      <table class="table table-striped">
        <tr>
          <th  class="column-title">Name</th>
          <th class="column-title">Description</th>
          <th class="column-title">Word Count</th>
          <th class="column-title"># Players played</th>
          <th></th>
        </tr>
        <% @snippets_pop.each do |snippet| %>
          <tr class='clickable-row' data-href='/snippets/<%= snippet.id %>'>
            <td><%= link_to( snippet.name, snippet_path(snippet)) %></td>
            <td><%= truncate(snippet.description, length: 100) %></td>
            <td><%= snippet.word_count %></td>
            <td><%= snippet.users_played %></td>
            <td><button class="btn btn-default">Play</button></td>
          </tr>
        <% end %>
        <% @snippets.each do |snippet| %>
          <% if !@snippets_pop.include? snippet%>
            <tr class='clickable-row' data-href='/snippets/<%= snippet.id %>'>
              <td><%= link_to( snippet.name, snippet_path(snippet)) %></td>
              <td><%= truncate(snippet.description, length: 100) %></td>
              <td><%= snippet.word_count %></td>
              <td><%= snippet.users_played %></td>
              <td><button class="btn btn-default">Play</button></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>

  <div class="right-side">
    <div class="div-language-score-board">
      <h3>Score Board</h3>
      <table class="table table-striped">
        <tr>
          <th>#</th>
          <th> Username </th>
          <th> Snippet </th>
          <th> Score </th>
        </tr>
        <% if @attempts.empty? %>
        <tr>
          <td> --- </td>
          <td> --- </td>
          <td> No entries </td>
          <td> --------- </td>
        </tr>
        <% else %>
          <% @attempts.each_with_index do |attempt, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><a href="/users/<%= attempt.user.id %>"><%= attempt.user.username %></a></td>
            <td><%= link_to( attempt.snippet.name, snippet_path(attempt.snippet)) %></td>
            <td><%= attempt.score %></td>
          </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>

app/views/snippets/ruby.html.erb
<div class="language-container">
  <div class="back-btn">
    <a href="/languages"><button class="btn-back">Back To Languages</button></a>
  </div>
  <div class="left-side">
    <h3>Ruby Snippets</h3>
    <div class="div-snippets-list">
      <table class="table table-striped">
        <tr>
          <th  class="column-title">Name</th>
          <th class="column-title">Description</th>
          <th class="column-title">Word Count</th>
          <th class="column-title"># Players played</th>
          <th></th>
        </tr>
        <% @snippets_pop.each do |snippet| %>
          <tr class='clickable-row' data-href='/snippets/<%= snippet.id %>'>
            <td><%= link_to( snippet.name, snippet_path(snippet)) %></td>
            <td><%= truncate(snippet.description, length: 100) %></td>
            <td><%= snippet.word_count %></td>
            <td><%= snippet.users_played %></td>
            <td><button class="btn btn-default">Play</button></td>
          </tr>
        <% end %>
        <% @snippets.each do |snippet| %>
          <% if !@snippets_pop.include? snippet%>
            <tr class='clickable-row' data-href='/snippets/<%= snippet.id %>'>
              <td><%= link_to( snippet.name, snippet_path(snippet)) %></td>
              <td><%= truncate(snippet.description, length: 100) %></td>
              <td><%= snippet.word_count %></td>
              <td><%= snippet.users_played %></td>
              <td><button class="btn btn-default">Play</button></td>
            </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>

  <div class="right-side">
    <div class="div-language-score-board">
      <h3>Score Board</h3>
      <table class="table table-striped">
        <tr>
          <th>#</th>
          <th> Username </th>
          <th> Snippet </th>
          <th> Score </th>
        </tr>
        <% if @attempts.empty? %>
        <tr>
          <td> --- </td>
          <td> --- </td>
          <td> No entries </td>
          <td> --------- </td>
        </tr>
        <% else %>
          <% @attempts.each_with_index do |attempt, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><a href="/users/<%= attempt.user.id %>"><%= attempt.user.username %></a></td>
            <td><%= link_to( attempt.snippet.name, snippet_path(attempt.snippet)) %></td>
            <td><%= attempt.score %></td>
          </tr>
          <% end %>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/snippets/show.html.erb
  <%= stylesheet_link_tag "snippets/show" %>

  <input type="hidden" name="snippet_id" value="<%= params[:id] %>">
  <input type="hidden" name="snippet_length" value="<%= @array.length-1 %>">
  <input type="hidden" name="snippet_word_count" value="<%= @snippet.word_count %>">

  <div class="snippets-show-wrapper">

    <section class="sidebar">

      <h3 class="btn-back-snippets"><a href="/languages/<%= @snippet.language %>"><- back to snippets</a></h3>

      <p><b><%= @snippet.name %></b></p>
      <p><%= @snippet.description %></p>

      <hr>

      <% if !!session[:user_id] %>
        <!-- History -->
        <h3>History</h3>
        <table class="table table-striped">
          <tr>
            <th>WPM</th>
            <th>Time</th>
          </tr>
          <% @history.each_with_index do |attempt, i| %>
            <tr>
              <td><%= attempt.score %></td>
              <td><%= @time_played[i] %></td>
            </tr>
          <% end %>
        </table>
      <% end %>

      <!-- Leaderboard -->
      <h3>Leaderboard</h3>
      <table class="table table-striped">
        <tr>
          <th>Rank</th>
          <th>Player</th>
          <th>WPM</th>
        </tr>
        <% @leaderboard.each_with_index do |attempt, i| %>
          <tr>
            <td><%= i+1 %></td>
            <td><a href="/users/<%= attempt.user.id %>"><%= attempt.user.username %></a></td>
            <td><%= attempt.score %></td>
          </tr>
        <% end %>
      </table>
    </section>

    <section class="header">
      <p><%= @header_snippet_name %></p>
    </section>

    <section class="snippet">
      <div class="snippet-row"><% for i in 1..@array.count("\n")+1 do %><span><%= i.to_s %><br></span><% end %></div>
      <div class="snippet-body"><% @array.each do |char| %><span><% if char == "\n" %>&nbsp;<br><% elsif char == " " %>&nbsp;<% else %><%= char %><% end %></span><% end %></div>
      <div style="clear: both;"></div>

      <!-- Win Modal -->
      <div id="winModal" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
          <p>Finish!</p>
          <p>WPM: <span></span></p>
          <br>
          <a href="/snippets/<%= params[:id] %>"><button class="btn btn-default playagain">Play again</button></a>
          <% if !session[:user_id] %>
            <a href="/users/new"><button class="btn btn-default signup">Sign up to save your scores</button></a>
          <% end %>
        </div>

      </div>

      <!-- Error Modal -->
      <div id="errorModal" class="modal">
        <div class="modal-content">
          <p>Error. Press backspace key.</p>
        </div>
      </div>

      <!-- Start Modal -->
      <div id="startModal" class="modal">
        <div class="modal-content">
          <p>Press first key to start.</p>
        </div>
      </div>

    </section>

    <section class="footer">
      <div class="timer">
        <p><b>Timer: <span>0:00</span></b></p>
      </div>
    </section>
  </div>

  <%= javascript_include_tag "snippets/show" %>